### ISSUE TITLE
Securing Kheops using self-signed certificates

### ISSUE THREAD

**Issue by mlenarsic** [OsiriX-Foundation/KheopsNginx#1]
Hi,
I would like to setup the Kheops nginx using a self-signed certificate. Is that possible and how would I go about creating and installing self signed SSL certificates? What adjustments need to be made to the letsencrypt enabled image?

Thank you.

**Comment by spalte** [comment]
Hello,

I just wrote some documentation on how to use existing certificates. Let me know if you need any additional help.

https://docs.kheops.online/docs/installation#using-a-custom-certificate

Cheers,
Joël

**Comment by mlenarsic** [comment]
Hey,

thank you for the quick response and the help. I am having a new problem however. After I login into Kheops, every API request that the frontend makes fails with the response code 502 bad gateway. 

Best,
Maj

**Comment by spalte** [comment]
Hi,

It's hard to say what is going on with just that information. When I need to debug a configuration, the first thing I do is to see if all the docker containers are running, if some were not able to start up, or if some have crashed.

```shell
docker ps -a
```

If any have crashed, you can see if maybe there is some explanation in the logs.

```shell
docker logs {crashed_container}
```

If all the containers are running, it is usually worthwhile to look in the kheopsauthorization or kheopsdicomwebproxy logs.

For example:
```shell
docker exec -it kheopsauthorization bash
cd logs
cat catalina.2020-10-15.log
```

You might be able to see some stack traces I the logs. Feel free to send them my way if you are not able to understand them.

Cheers,
Joël

**Comment by mlenarsic** [comment]
Hey,

none of the containers is crashing, but in the kheopsauthorizations logs the following error appears. I am not sure how to deal with this.

> 16-Oct-2020 21:00:23.951 SEVERE [http-nio-8080-exec-3] online.kheops.auth_server.mapper.OtherExceptionMapper.toResponse id:7I3xabCythHtIKpYL57l
	online.kheops.auth_server.accesstoken.DownloadKeyException: Unable to download the jwks_uri, configuration URL:https://keycloak.test:8443/auth/realms/kheops/.well-known/openid-configuration
		at online.kheops.auth_server.accesstoken.OidcAccessToken$Builder.getJwksURL(OidcAccessToken.java:159)
		at online.kheops.auth_server.accesstoken.OidcAccessToken$Builder.build(OidcAccessToken.java:89)
		at online.kheops.auth_server.accesstoken.OidcAccessToken$Builder.build(OidcAccessToken.java:79)
		at online.kheops.auth_server.accesstoken.AccessTokenVerifier.authenticateAccessTokens(AccessTokenVerifier.java:61)
		at online.kheops.auth_server.accesstoken.AccessTokenVerifier.authenticateAccessToken(AccessTokenVerifier.java:24)
		at online.kheops.auth_server.filter.SecuredFilter.filter(SecuredFilter.java:54)
		at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:108)
		at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:44)
		at org.glassfish.jersey.process.internal.Stages.process(Stages.java:173)
		at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:245)
		at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
		at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
		at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
		at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
		at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
		at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
		at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
		at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
		at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
		at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
		at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
		at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
		at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:834)
	Caused by: javax.ws.rs.ProcessingException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
		at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:260)
		at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:254)
		at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:750)
		at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
		at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
		at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
		at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
		at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:748)
		at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:404)
		at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:300)
		at online.kheops.auth_server.accesstoken.OidcAccessToken$Builder.getJwksURL(OidcAccessToken.java:157)
		... 44 more
	Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
		at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
		at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:645)
		at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:464)
		at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360)
		at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
		at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
		at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
		at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
		at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
		at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1144)
		at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1055)
		at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:395)
		at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
		at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
		at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
		at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
		at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
		at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
		at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:366)
		at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:258)
		... 54 more
	Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
		at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
		at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
		at java.base/sun.security.validator.Validator.validate(Validator.java:264)
		at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
		at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
		at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
		at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:629)
		... 72 more
	Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
		at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
		at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
		at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
		at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
		... 78 more

**Comment by spalte** [comment]
Hi,

kheopsauthorization needs to download the OpenID Provider (Keycloak) RSA public key in order to validate Access Tokens. It knows where to go using the URL specified in the KHEOPS_OIDC_PROVIDER environment variable.

My interpretation of the stack trace is that kheopsauthorization is able to connect to the OpenID Provider, but as you mentioned, you are using a self-signed certificate, and the Tomcat that runs kheopsauthorization refuses to establish the https connection.

I see two options. The first would be to give kheopsauthorization access to the OpenID Provider through an a non-https connection. You would use KHEOPS_OIDC_PROVIDER to pass the http:// url.

The second option is to create a derived container from kheop-authorization that includes the CA used for your self-signed certificate.

```Dockerfile
FROM osirixfoundation/kheops-authorization:v0.9.5

COPY ca.pem ca.pem
RUN keytool -importcert -alias customCA -cacerts -storepass changeit -noprompt -file ca.pem
```

Let me know if this makes sense, or if there is anything else I can help with.

Cheers,
Joël

**Comment by mlenarsic** [comment]
The derived container made it work. Thank you!
